name: C/C++ CI

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: [self-hosted]
    
    steps:
    - uses: actions/checkout@v1
    - name: make build dir
      run: mkdir build
    - name: cmake 
      working-directory: build
      run: cmake ..
    - name: make
      working-directory: build
      run: make
    - name: unit tests
      run: tests/unit_test/RunLibCppUnitTest.sh
    - name: integration tests
      run: tests/integration_tests/RunIntegrationTests.sh
  
